### ISSUE TITLE
Compatibility with openEO API v0.4

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#17]
The hub doesn't fully support API v0.4 and hence multiple information are missing, for example processes, collections, version etc. We can probably add more migrations to the js-commons to support this.

**Comment by m-mohr** [comment]
> We can probably add more migrations to the js-commons to support this.

Migrations for capabilities, output formats and service types are available in vue-components@0.3.5 and js-commons@0.3.4, so 0.4 compatibility should be relatively easy to implement.

**Comment by christophfriedrich** [comment]
Because almost everything is handled by the vue-components (and thus the migrations in js-commons), I think the output formats were the last thing that was missing -- at least in the Discover section.

That said, the Search section of course has quite a few more things that would need an update -- but since I'll soon re-write searching anyway (the new "filter" area within the Discover section), I don't see a point in investing (a lot of) time into fixing that old search.

**Comment by christophfriedrich** [comment]
:arrow_right: As discussed, I'll add/fix the {most obvious|easier} things (e.g. add radioboxes for 0.4.x backend versions, fix output format search) and then that should be enough.

**Comment by christophfriedrich** [comment]
The only thing that doesn't work yet with v0.4 is the "search by process graph" feature. I would argue to leave it like that for now because:

> Since the process graphs massively changed between openEO API v0.3 and v0.4, adapting this type of search would be a very big task and is therefore postponed, since the search feature will soon undergo big changes anyway.

*(quote from commit message of ab6d44b)*

:arrow_right: I added a note to the frontend that only v0.3 process graphs are supported.

All other aspects of the Hub should now be fully compatible to openEO API v0.4:
- backends are correctly crawled (if they return spec-compatible replies)
- all data is displayed in the Discovery section (new descriptions, changed output formats, changed collections and processes, added functionality paths, ...)
- all queries that may be produced by the Search section work (except "search by process graph", as stated above)

I would therefore close this issue or rename it to "Fix searching by openEO API v0.4 process graphs".

**Comment by m-mohr** [comment]
Great.
I'm tempted to just remove process graph search for now, but I'll leave this to your decision.

Issue: Close it and open a new one is the cleaner approach, I think. ;-)

**Comment by christophfriedrich** [comment]
I thought "How much work can it be" -- and eventually (after [of course] more work than expected) it turned out that the solution wasn't difficult at all. So now that last feature is also available for v0.4! :tada:

:arrow_right: Full support for v0.4
:arrow_right: No need to decide whether to leave the incomplete search in the release or not
:arrow_right: No separate issue necessary
:)
