### ISSUE TITLE
Show UDF capabilities

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#28]
The Hub should also show the UDF capabilities as available in /udf_runtimes.

Originated in #1.

**Comment by m-mohr** [comment]
Needs a component in openeo-vue-components.

**Comment by m-mohr** [comment]
Implemented, see https://github.com/Open-EO/openeo-vue-components/issues/12. Will be part of the next release.

**Comment by m-mohr** [comment]
Released with 1.0.0-beta.6

**Comment by christophfriedrich** [comment]
Thanks for the component -- having it made implementing UDF runtimes in the Hub very straightforward! _(except for the little reason I made the PR over there :wink:)_

For now I'll leave this issue open though because I'll still have to update the package.json with the correct vue-components version number. I worked with a locally linked version of its most recent dev branch -- for that to work I'd have to wait for the beta.7, right? Or I change the import and use the already released beta.6?

**Comment by m-mohr** [comment]
The code is correct, so why not just use beta.6? The documentation change has no further impact on the implementation, right?

**Comment by christophfriedrich** [comment]
You explicitly pointed me to the release notes of beta.6 which says:

> Note: UdfRuntime is missing from the package export and thus the components needs to be imported directly. This will be fixed in the next version.

I locally used the dev branch of vue-components which already has the commit Open-EO/openeo-vue-components@d8dde84 "Add missing UdfRuntime component to default package export".

So I thought my code + beta.6 wouldn't work because I would have to adapt the import?

**Comment by m-mohr** [comment]
You already import the component directly (``import UdfRuntime from './components/UdfRuntime.vue';``), so no issue and beta.6 can be used.

**Comment by m-mohr** [comment]
How do you import the component?

**Comment by christophfriedrich** [comment]
> You already import the component directly

I believe I don't, but these imports always really confuse me...

> How do you import the component?

This way:

https://github.com/Open-EO/openeo-hub/blob/83b8afc50a351873795cb26c31a7635fc07b9e90/src/components/Backend.vue#L99

**Comment by m-mohr** [comment]
This is the direct import you can use in beta.6: 
`import UdfRuntime from '@openeo/vue-components/components/UdfRuntime.vue';`

**Comment by christophfriedrich** [comment]
Thanks, I was about to commit it but just before clicking the button realised that I'm only using UdfRuntime**s**, and not the singular UdfRuntime, so I don't even need this. Sorry for Pferde scheu machen :see_no_evil:

I just need to bump up my dependencies from beta.4 to beta.6 and we should be ready to go!
