### ISSUE TITLE
Show descriptions for BackendGroups

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#29]
The back-end descriptions are missing and should be shown, similarly to your screenshot in #14:

![image](https://user-images.githubusercontent.com/8262166/63160780-e7adf500-c01e-11e9-94db-0270a47856db.png)

Da die Beschreibungen länger sein können (und Markdown unterstützen -> Description component in vue-components), sollten nur ein paar Zeilen (zw. 3 und 5?) angezeigt werden und der Rest erst beim ausklappen. Das mehr Beschreibung zur Verfügung steht sollte in der UI sichtbar sein (... oder langsames Ausblenden, wie man es von einigen Zeitungen kennt).

**Comment by m-mohr** [comment]
Here's code for fading out, which I am using in the new UdfRuntimes component.

```
.vue-component.runtimes .collapsible .runtime-details {
	max-height: 3em;
	overflow-y: hidden;
	position: relative;
}
.vue-component.runtimes .collapsible.expanded .runtime-details {
	max-height: fit-content;
}
.vue-component.runtimes .collapsible .runtime-details:before {
	content: '';
	width: 100%;
	height: 100%;    
	position: absolute;
	left: 0;
	top: 0;
	background: linear-gradient(rgba(255,255,255,0) 1em, white);
}
.vue-component.runtimes .collapsible.expanded .runtime-details:before {
	background: transparent;
}
```

**Comment by christophfriedrich** [comment]
Since implementing the grouping of backends (with tabs for each version), the "top-level component" within the `DiscoverySection` (and thus the component that is visible when opening the site) is `BackendGroup`. The individual `Backend`s are hidden within the `BackendGroup`s' collapse areas.

To implement a start screen like in the screenshot, it must be decided which description should be displayed by such a `BackendGroup`? It may contain multiple backends with different descriptions...

**Comment by m-mohr** [comment]
Until #202 is available in 1.0, we couldjust use the most recent one (i.e. the description of the back-end with the highest version number).

**Comment by christophfriedrich** [comment]
With 29affc2, **backends** now show descriptions.

But **backend groups** (i.e. those components you see when you open the Hub) don't - because @m-mohr and I didn't like that the description would be shown in the initial state, but disappear upon expanding. We can again think about that for Hub v0.4 :arrow_right: changing title and milestone.

Long descriptions are (for now) not handled via a fancy fade-out or what not, but a simple scrollbar via `y-overflow: auto` once their height exceeds 15em. Please open another issue if you'd like to change this.

**Comment by m-mohr** [comment]
Looking again over the Hub homepage, I think it's cleaner to not show the descriptions. It would really clutter the overview page. Let's open an issue whenever it becomes an actual issue. This is good for now, so closing.

**Comment by christophfriedrich** [comment]
IMO the screenshot at the top looks quite neat, not overly cluttered. I would've been fine with realising this for the new field from Open-EO/openeo-api#202. But I'm also not overly sad if it's not included :man_shrugging:
