### ISSUE TITLE
No "well-known URL" for back-ends shown

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#69]
Currently the Hub exposes the URLs for each of the versions, e.g. `https://openeo.vgt.vito.be/openeo/1.0`. That shouldn't be the case. The URLs to promote are the "well-known" one used in clients, for example `https://openeo.vgt.vito.be`. We can still show the direct URLs somewhere, but they should be a bit more hidden and the "well-known" URLs should be the main entry point.

**Comment by christophfriedrich** [comment]
From a technical person's point of view I liked it as it was, but okay, if our policy is different I will change it.

My first idea then: Output the well-known URL once for the whole backend group, between the heading and the version pills, like this:

> ![image](https://user-images.githubusercontent.com/17781682/83017448-f69ceb80-a023-11ea-9ba2-e1b5610b1571.png)

Doesn't look as neat though.

Option 2: Leave it as before, but output the well-known URL instead of the direct one. But that's repetitive information that doesn't change across tabs.

Do you have a preference?

---

> We can still show the direct URLs somewhere, but they should be a bit more hidden

Hm. What would be a "more hidden" place for you? I can't think of one that doesn't require adding a new sub-heading (e.g. "Technical details" below "Billing information").

---

While we're at it: Which URL should be fed to the web editor via the "Open in openEO web editor" button?

**Comment by m-mohr** [comment]
Yeah, I thought about this, too, but couldn't come up with a good solution yet so that's why nothing is proposed above.

I quickly thought about the version numbers, too. Those are relative obscure to a non-technical person (a normal user). Usually a normal user probably only wants to see the info about the latest production-ready version, so I thought about moving the tabs to the bottom or somewhere not so prominent. Then the URL would't look so off, but I'm not convinced yet.

Re Web Editor: That's somewhat depending on the future of the Web Editor. I could see that passing the version at some point is possible, because you can't choose the version yet and we handle things with different deployments. For VITO just passing the well-known URL doesn't work as they have 0.4.0, 0.4.1, 0.4.2 and with well-known URL the Web Editor always connects to 0.4.2. So it should be the well-known URL, but at the moment it doesn't quite work out yet. Bummer.

**Comment by christophfriedrich** [comment]
Ok, then I will implement the screenshot variant for now. And leave the web editor part as it is.

In the rest what you're writing I spot a more general issue, so I opened one to discuss that separately (#70).
