### ISSUE TITLE
Edge arrow design issue 

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#74]
In Edge 44 / EdgeHTML 18 the arrows look very weird:

![image](https://user-images.githubusercontent.com/8262166/85317732-2f16d480-b4bf-11ea-80b3-a51a4ece788f.png)

The arrows pointing down look good, but the arrows pointing right are blue and look weird.

**Comment by christophfriedrich** [comment]
Sometimes I like emojis, sometimes I hate them... I used the classic "black right pointing triangle" and "black down-pointing triangle" unicode symobls. They should all look alike: https://graphemica.com/blocks/geometric-shapes But since emojis came up it has been abused as "play button", see https://emojipedia.org/play-button/

This probably comes up now because of the font rule change in #40 which emphasizes system fonts and those usually have the fancy emojis instead of the simple unicode glyphs...

I could:
1. wrap the symbols in a `<span>` and style them with the same font
2. set the whole website to one font
3. use images
4. use SVGs

I don't like option 3, no. 1 is okay, no. 4 a bit over the top.

TBH I'd prefer to have ONE font EVERYWHERE on ALL devices (i.e. option 2) instead of this system-font thing, so that the website looks the same everywhere. But that's kinda against #40...

**Comment by m-mohr** [comment]
> This probably comes up now because of the font rule change in #40 

I don't think so. It's the state of the deployed Hub which doesn't have #40 integrated yet, so it's based on your previous font!

I just tried to style it with a simple color: black or change the font-family in the DevTools, which did not work. So this is (mostly?) independent of the chosen font! It seems the only options are 3 and 4, which I dislike as it also has influence on the Vue Components. For consistency (may it be the blue thing or something black), I could imagine that we actually rotate the arrow in CSS so that it doesn't switch between blue and black at least.

**Comment by christophfriedrich** [comment]
> It's the state of the deployed Hub which doesn't have #40 integrated yet

Oh true :thinking: 

I don't have a Windows machine at hand right now to test with Edge, but I'll do that soon.

I'll probably go for your option 5.

> as it also has influence on the Vue Components

How do you mean that? Do the components use those triangles too?

**Comment by m-mohr** [comment]
Nevermind, I just realized that vue-components use another arrow: ▸(which is not a Play button in edge, so that's option 6)

**Comment by christophfriedrich** [comment]
Finally did that search&replace and tested it on my Windows laptop.
