### ISSUE TITLE
Expanding processes/collections reduces number of processes/collections

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#78]
For mostly all back-ends expanding the list of processes or collections reduces the number of processes/collections. 

I guess that this may happen because it removes incompatible processes/collections on expansion?

Before:
![image](https://user-images.githubusercontent.com/8262166/89167211-662adc00-d57b-11ea-9cd3-63114a35637d.png)

After:
![image](https://user-images.githubusercontent.com/8262166/89167116-48f60d80-d57b-11ea-8c11-7dbdb82473bd.png)

Before:
![image](https://user-images.githubusercontent.com/8262166/89167143-514e4880-d57b-11ea-881f-4a40d23b87c2.png)

After: 
![image](https://user-images.githubusercontent.com/8262166/89167164-5612fc80-d57b-11ea-922c-fc5bdfbf1935.png)

**Comment by christophfriedrich** [comment]
Thank you very much for reporting this observation! The initial count is the correct one, it is taken from the `backends` database table*. When expanding, the rest of the data is loaded from the dedicated `collections` and `processes` tables respectively. And since I "fixed" #76 in 83b8afc, those were populated incorrectly during crawling...

---
*\* Note: The Hub uses a MongoDB, so technically it's not a "table" but a "collection", but I find this terminology confusing when also talking about openEO collections in the same context.*
